 Plotting timeseries data
========================================================
Jennifer C. Stearns,
`r as.character(format(Sys.Date(), format="%B %d, %Y"))`

```{r, warning=FALSE, message=FALSE}
setwd("~/Documents/Baby_mi_data/")
library(knitr)
opts_chunk$set(cache=FALSE)
library(ggplot2)
library(lme4)
library(grid)
library(reshape2)
```

```{r}
meta_table<-read.csv("sub_meta.csv", row.names = 1, na.strings="#NULL!")

L6 <- read.csv("SPE_GBS_L6_nRoot.csv",row.names=1,check.names=FALSE)

L6 <- subset(L6,rowSums(L6) > 0.01)
L6 <- L6[order(rowSums(L6),decreasing = TRUE),]

#Transpose the data to have sample names on rows
L6 <-t(L6)

meta.b <- meta_table[rownames(L6),]

# combine meta
final.b <- data.frame(meta.b, L6)
```

```{r}
noIPA <- subset(final.b, ipa_indication==1)
t10 <- noIPA[,c(1,3,24:33)]
t10.l <- melt(t10, id.vars=c("PID","actual_age"), value.name="value", variable.name="Taxa")
```

```{r}
pdf("timeseries.pdf",height=10,width=20)
p <- ggplot(t10.l, aes(x=actual_age, y=value, group=Taxa, colour=Taxa)) + geom_line(size=2)
p + facet_wrap(~PID)
dev.off()
```